# Generated by Django 4.2.7 on 2023-11-25 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='Restaurant',
            new_name='restaurant',
        ),
    ]
